spring.application.name=urbanclonebackend

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=${PORT:8080}
jwt.secret=urbancloneverysecretkeyurbancloneverysecretkey1234


## only enable for local
#spring.application.name=urbanclonebackend
#spring.profiles.active=local